# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '2a64678f-b255-4a86-9dc9-ccd699004e1c'
  imageRepository: 'buggycore5'
  containerRegistry: 'tatacr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Print params, test, build and push stage
  jobs:
  # print all the parameters
  - job: Print_Parameters
    displayName: Print Parameters
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo 'Print all parameters: '
          echo 'Service connection: ' $(dockerRegistryServiceConnection)
          echo 'Image repository: ' $(imageRepository)
          echo 'Azure container registry: ' $(containerRegistry)
          echo 'Dockerfile path: ' $(dockerfilePath)
          echo 'Build ID: ' $(tag)
          echo 'VM image name: ' $(vmImageName)
  - job: Build
    displayName: Build
    dependsOn: Print_Parameters
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest          

  # Each build must finish with artifact task 
  # because output will be used in Release Pipeline
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/BuggyBits/Deployments/Kubernetes/'
        ArtifactName: 'drop'
        publishLocation: 'Container'